### ISSUE TITLE
Margin use

### ISSUE THREAD

**Issue by wtyhub** [CHENGY12/DMML#2]
Why I didn't find the use of margin in your code。It is removed

**Comment by wtyhub** [comment]
![image](https://user-images.githubusercontent.com/29724042/75873005-458f1680-5e63-11ea-9da3-fdb86816777c.png)

**Comment by trzhang0116** [comment]
Hello. This is mainly because that we found by using cosine distance instead of Euclidean distance, we were able to achieve slightly better performance in additional experiments we conducted after paper publication. Although the margin strategy improves the performance when Euclidean distance is used, we have not tried to combine it with cosine distance. Therefore, in the current version of code we substitute the Euclidean distance with cosine distance and remove the margin.

**Comment by wtyhub** [comment]
Thanks for your reply
